// SIGNUP ACTION TYPES;  
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";


// LOGIN ACTION TYPES
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//LOGOUT ACTION TYPE
export const LOGOUT = 'LOGOUT';

// RESET PASSWORD ATTEMPT TYPES 
export const RESET_ATTEMPT_REQUEST='RESET_ATTEMPT_REQUEST';
export const RESET_ATTEMPT_SUCCESS='RESET_ATTEMPT_SUCCESS';
export const RESET_ATTEMPT_FAILURE='RESET_ATTEMPT_FAILURE';

// RESET PASSWORD REQUEST TYPES
export const RESET_PASSWORD_REQUEST='RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE='RESET_PASSWORD_FAILURE';


// REPORT CREATION TYPES;
export const NEW_REPORT_REQUEST = 'NEW_REPORT_REQUEST';
export const NEW_REPORT_FAILED = 'NEW_REPORT_FAILED';
export const NEW_REPORT_SUCCESS = 'NEW_REPORT_SUCCESS';

export const GET_ALL_REPORTS_STARTING = 'GET_ALL_REPORTS_STARTING';
export const GET_ALL_REPORTS_SUCCESS = 'GET_ALL_REPORTS_SUCESS';
export const GET_ALL_REPORTS_FAILED = 'GET_ALL_REPORTS_FAILED';
export const GET_ALL_REPORTS_ENDING = 'GET_ALL_REPORTS_ENDING';

export const GET_SINGLE_REPORT_STARTING = 'GET_SINGLE_REPORT_STARTING';
export const GET_SINGLE_REPORT_SUCCESS = 'GET_SINGLE_REPORT_SUCCESS';
export const GET_SINGLE_REPORT_FAILED = 'GET_SINGLE_REPORT_FAILED';
export const GET_SINGLE_REPORT_ENDING = 'GET_SINGLE_REPORT_ENDING';

// SHAREABLE CLOSE MESSAGE ACTION
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
