// SIGNUP ACTION TYPES;  
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";


// LOGIN ACTION TYPES
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";


// RESET PASSWORD ATTEMPT TYPES 
export const RESET_ATTEMPT_REQUEST='RESET_ATTEMPT_REQUEST';
export const RESET_ATTEMPT_SUCCESS='RESET_ATTEMPT_SUCCESS';
export const RESET_ATTEMPT_FAILURE='RESET_ATTEMPT_FAILURE';

// RESET PASSWORD REQUEST TYPES
export const RESET_PASSWORD_REQUEST='RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE='RESET_PASSWORD_FAILURE';


// SHAREABLE CLOSE MESSAGE ACTION
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
